# -*- coding: utf-8 -*-
"""DL-1(Section 1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rd4j23yXZoID_iqeNR9BQoMNM3xJMXPQ
"""

import requests
import re
import csv
from bs4 import BeautifulSoup

url = "https://www.wikihow.com/Special:Randomizer"

response = requests.get(url)
html_content = response.content

soup = BeautifulSoup(html_content, "html.parser")
artcile_title = soup.find("title").text.strip()
print(artcile_title)

subheadings = []
paragraphs = []
steps = soup.find_all("div",{"class":"step"})
for step in steps:
    subheadings_element = step.find("b")
    if (subheadings_element is not None):
        subheadings_text = subheadings_element.text.strip().replace("\n","")
        subheadings_text = subheadings_text.encode('ascii',errors='ignore').decode()
        subheadings_text = re.sub(r"","",subheadings_text)
        print(subheadings_text)
        subheadings.append(subheadings_text)

        subheadings_element.extract()
        for span_tag in step.find_all("span"):
            span_tag.extract()

        paragraph_text = step.text.strip().replace("\n"," ").replace("  "," ")
        paragraph_text = paragraph_text.encode('ascii',errors='ignore').decode()
        paragraph_text = re.sub(r"","",paragraph_text)
        print(paragraph_text)
        paragraphs.append(paragraph_text)

if len(subheadings):
        with open('wikiHow.csv', mode='a', newline='', encoding='utf-8') as csv_file:
            writer = csv.writer(csv_file)
            for i in range(len(subheadings)):
                writer.writerow([artcile_title, subheadings[i], paragraphs[i]])

for count in range(4000):
    url = 'https://www.wikihow.com/Special:Randomizer'
    response = requests.get(url)
    html_content = response.content
    soup = BeautifulSoup(html_content, 'html.parser')

    article_title = soup.find('title').text.strip()
    print(article_title + " " + str(count))

    subheadings = []
    paragraphs = []

    steps = soup.find_all('div', class_='step')
    for step in steps:
        subheading_element = step.find('b')
        if subheading_element is not None:
            subheading_text = subheading_element.text.strip().replace('\n', '')
            subheading_text = subheading_text.encode('ascii', errors='ignore').decode()
            subheading_text = re.sub(",","", subheading_text)
            subheadings.append(subheading_text)
            subheading_element.extract()

        for span_tag in step.find_all('span'):
            span_tag.extract()

        paragraph_text = step.text.strip().replace('\n', '')
        paragraph_text = paragraph_text.encode('ascii', errors='ignore').decode()
        paragraph_text = re.sub(",","", paragraph_text)
        paragraphs.append(paragraph_text)

    if len(subheadings):
        with open('/content/wikiHow.csv', mode='a', newline='', encoding='utf-8') as csv_file:
            writer = csv.writer(csv_file)
            for i in range(len(subheadings)):
                writer.writerow([article_title, subheadings[i], paragraphs[i]])